"""
==============
OpenHD Codegen
==============

This does "codegen.to_source" with some bug fixes of the original code
"""

from astor import SourceGenerator, get_op_symbol

def to_source(node, indent_with=' ' * 4, add_line_information=False):
    """This function can convert a node tree back into python sourcecode.
    This is useful for debugging purposes, especially if you're dealing with
    custom asts not generated by python itself.
    It could be that the sourcecode is evaluable when the AST itself is not
    compilable / evaluable.  The reason for this is that the AST contains some
    more data than regular sourcecode does, which is dropped during
    conversion.
    Each level of indentation is replaced with `indent_with`.  Per default this
    parameter is equal to four spaces as suggested by PEP 8, but it might be
    adjusted to match the application's styleguide.
    If `add_line_information` is set to `True` comments for the line numbers
    of the nodes are added to the output.  This can be used to spot wrong line
    number information of statement nodes.
    """
    generator = OpenHDSourceGenerator(indent_with, add_line_information)
    generator.visit(node)

    return ''.join(generator.result)

class OpenHDSourceGenerator(SourceGenerator):
    def visit_BinOp(self, node):
        self.write('(')
        self.visit(node.left)
        self.write(get_op_symbol(node.op, ' %s '))
        self.visit(node.right)
        self.write(')')
